#!/usr/bin/env python3
"""Extract the compiled UI font's character range into a committed fact.

    python3 scripts/gen-font-range.py

The range is a property of the build: LVGL's generated font source records it on
the `Opts:` line the font converter writes. Reading it there is correct, but it
means every guard that needs it also needs firmware/.pio/libdeps to exist - so
scripts/verify.sh --quick, and therefore the pre-commit hook, could not run in a
fresh clone until someone ran `pio pkg install`. A hook that does not work out of
the box is a hook that gets uninstalled.

So the range is extracted once, committed, and read from here. That is not a
second copy of the fact going stale: scripts/check-generated.py re-runs this
generator and fails if the committed file disagrees, exactly as it does for the
TigerTag reference header. CI has the library on disk and proves the fact on
every push; the hook reads the proven fact and needs no build tree.

Exits 3, distinctly, when the LVGL source is not present - "I could not check"
is a different answer from "it does not match", and check-generated.py reports
them differently.
"""

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "scripts" / "font_range.json"

SOURCE_UNAVAILABLE = 3


def main() -> int:
    sources = sorted((REPO / "firmware" / ".pio" / "libdeps").glob(
        "*/lvgl/src/font/lv_font_montserrat_*.c"))
    if not sources:
        print("LVGL font source not present under firmware/.pio/libdeps - "
              "run 'pio pkg install' in firmware/ to verify the range here",
              file=sys.stderr)
        return SOURCE_UNAVAILABLE

    specs = {}
    for src in sources:
        # Only the banner: these files are hundreds of kilobytes of glyph data.
        m = re.search(r"-r\s+([0-9A-Fa-fx,\-]+)", src.read_text(errors="replace")[:4096])
        if m:
            specs[src.name] = m.group(1)

    if not specs:
        print(f"found {len(sources)} font source(s) but no '-r' range in any "
              "banner - the font converter's option line has changed shape",
              file=sys.stderr)
        return 1

    distinct = sorted(set(specs.values()))
    if len(distinct) > 1:
        # Every enabled size must carry the same glyphs, or a string is
        # drawable at 14 px and a blank box at 20 px.
        print("the enabled Montserrat sizes do not share one range:",
              file=sys.stderr)
        for name, spec in sorted(specs.items()):
            print(f"  {name}: {spec}", file=sys.stderr)
        return 1

    OUT.write_text(json.dumps({
        "_comment": "GENERATED by scripts/gen-font-range.py - do NOT edit by hand.",
        "spec": distinct[0],
        "read_from": sorted(specs)[0],
        "sizes": len(specs),
    }, indent=2) + "\n")
    print(f"OK -> {OUT.relative_to(REPO)}   ({distinct[0]}, "
          f"{len(specs)} font size(s) agree)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
