#!/usr/bin/env python3
"""Turn a PNG into the RGB565 C header the panel draws.

    python3 scripts/make-rgb565-header.py assets/TigerSpoolRFID-BootScreen.png \
        --name SPLASH --out firmware/include/splash.h

The boot screen is pushed to the panel before LVGL exists, straight from flash,
so it has to be a flat array of RGB565 words in the panel's own byte order.
This is what turns a design file into something the device can show.

**The input must already be the target pixel size.** Resizing is a design
decision — which crop, which interpolation, whether the logo still reads at that
size — and a converter that guesses at it produces something nobody chose. On
macOS: `sips -z 320 240 in.png --out out.png` (height then width).

Only the standard library is used, so there is nothing to install and CI can
re-run it to check the committed header still matches. Handles 8-bit truecolour
PNGs, with or without alpha, non-interlaced — which is what every design tool
exports by default. Anything else is refused by name rather than mis-decoded.
"""

import argparse
import pathlib
import struct
import sys
import zlib


def decode_png(data: bytes):
    """Return (width, height, rows) where each row is a list of (r, g, b)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")

    width = height = None
    colour_type = bit_depth = interlace = None
    idat = bytearray()

    pos = 8
    while pos < len(data):
        (length,) = struct.unpack(">I", data[pos:pos + 4])
        kind = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + length]
        pos += 12 + length                      # length + type + body + CRC

        if kind == b"IHDR":
            width, height, bit_depth, colour_type, _, _, interlace = \
                struct.unpack(">IIBBBBB", body)
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break

    if bit_depth != 8:
        raise ValueError(f"bit depth {bit_depth} — only 8 is supported")
    if colour_type not in (2, 6):
        raise ValueError(f"colour type {colour_type} — only truecolour (2) "
                         "and truecolour+alpha (6) are supported")
    if interlace:
        raise ValueError("interlaced PNG — re-export without Adam7")

    channels = 3 if colour_type == 2 else 4
    stride = width * channels
    raw = zlib.decompress(bytes(idat))

    # Undo the per-row filters. Each row is prefixed by its filter type, and
    # every filter refers to the reconstructed bytes to the left (a) and above
    # (b), so this has to run in order over the whole image.
    out = bytearray(stride * height)
    prev = bytearray(stride)
    at = 0
    for y in range(height):
        ftype = raw[at]; at += 1
        line = bytearray(raw[at:at + stride]); at += stride
        for i in range(stride):
            a = line[i - channels] if i >= channels else 0
            b = prev[i]
            c = prev[i - channels] if i >= channels else 0
            x = line[i]
            if ftype == 0:   line[i] = x
            elif ftype == 1: line[i] = (x + a) & 0xFF
            elif ftype == 2: line[i] = (x + b) & 0xFF
            elif ftype == 3: line[i] = (x + ((a + b) >> 1)) & 0xFF
            elif ftype == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (x + pred) & 0xFF
            else:
                raise ValueError(f"unknown row filter {ftype} on row {y}")
        out[y * stride:(y + 1) * stride] = line
        prev = line

    rows = []
    for y in range(height):
        row = []
        base = y * stride
        for x in range(width):
            i = base + x * channels
            row.append((out[i], out[i + 1], out[i + 2]))
        rows.append(row)
    return width, height, rows


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("png")
    ap.add_argument("--name", required=True, help="C identifier prefix, e.g. SPLASH")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    src = pathlib.Path(a.png)
    try:
        w, h, rows = decode_png(src.read_bytes())
    except ValueError as e:
        print(f"error: {src}: {e}", file=sys.stderr)
        return 1

    words = [rgb565(*px) for row in rows for px in row]

    lines = [
        f"// GENERATED by scripts/make-rgb565-header.py from {src.as_posix()}",
        "// - do NOT edit by hand.",
        "//",
        f"// {w}x{h} RGB565, {len(words) * 2} bytes of flash. Pushed to the panel",
        "// before LVGL exists, so it is a flat array rather than an LVGL image.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"static const uint16_t {a.name}_W = {w};",
        f"static const uint16_t {a.name}_H = {h};",
        f"static const uint16_t {a.name}_DATA[{len(words)}] PROGMEM = {{",
    ]
    for i in range(0, len(words), 12):
        lines.append("  " + " ".join(f"0x{v:04X}," for v in words[i:i + 12]))
    lines.append("};")

    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"OK -> {a.out}   ({w}x{h}, {len(words) * 2} bytes of flash)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
