#!/usr/bin/env python3
"""Turn a small web asset into the PROGMEM C string the device serves.

    python3 scripts/make-web-asset-header.py installer/tiger-icon.svg \
        --name TIGER_ICON_SVG --out firmware/include/web_assets.h

The pages the device serves are opened on a phone that is joined to the
device's OWN access point and therefore has no internet. Every byte the page
references has to come from the device: a `<img src="https://...">` renders as
an empty box, silently, on exactly the screen where someone is deciding whether
to type their password. So the asset ships in flash.

It is served from its own route rather than inlined as a data URI, so the HTML
stays small and the browser caches the artwork across the pages that use it.

Text is emitted as a C raw string literal, which keeps the header readable and
diffable - the point of committing a generated file at all. The delimiter is
checked against the content rather than assumed.
"""

import argparse
import pathlib
import sys

DELIM = "TTASSET"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("--name", required=True, help="C identifier, e.g. TIGER_ICON_SVG")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    src = pathlib.Path(a.source)
    try:
        text = src.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        print(f"error: {src}: {e}", file=sys.stderr)
        return 1

    if f'){DELIM}"' in text:
        print(f"error: {src} contains the raw-string delimiter )" + DELIM + '"',
              file=sys.stderr)
        return 1

    # An XML prolog is redundant once the bytes are served with a Content-Type,
    # and it costs flash on every device ever built.
    if text.startswith("<?xml"):
        text = text[text.index("?>") + 2:].lstrip()
    text = text.rstrip() + "\n"

    lines = [
        f"// GENERATED by scripts/make-web-asset-header.py from {src.as_posix()}",
        "// - do NOT edit by hand.",
        "//",
        "// Served by the device itself. The phone reading it is joined to the",
        "// device's access point and has no internet, so nothing here may be",
        "// fetched from anywhere else.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"static const char {a.name}[] PROGMEM = R\"{DELIM}(",
        text.rstrip("\n"),
        f"){DELIM}\";",
    ]

    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"OK -> {a.out}   ({len(text)} bytes of flash)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
